import zhLocale from 'element-ui/lib/locale/lang/zh-CN';


const zh = {
    ...zhLocale,
    deviceManage :{
        fileName:'文件名称',
    },
    message: {
        download:'下载',
        serialNumber: '序号',
        operate: '操作',
        locationManage: '位置管理',
        gisMonitoring: '农业监控',
        historyRoute: '历史轨迹',
        taskManage: '作业管理',
        vehicleManage: '车辆管理',
        infoManage: '信息管理',
        statistics: '统计报表',
        report: '统计报表',
        carManage:'车辆管理',
        positionManage:'位置管理',
        historyTrace:'历史轨迹',
        workManage:'作业管理',
        statisticsReport:'统计报表',
        historyDrive:'自动驾驶趋势图',
        StartTime:'开始时间',
        LeftRight:'左右偏移(m)',
        Behind:'前后偏移(m)',
        Width:'宽度(m)',
        EndTime:'结束时间',
        DriveInfo:'驾驶记录',
        Driving:'驾驶时段',
        Autopilot:'详细记录',
        DriveStatus: '驾驶状态',
        IMUData: 'IMU数据',
        LateralDeviation: '横向偏差',
        LateralDeviation1:'横向偏差(cm)',
        CourseAngleDeviation: '航向角偏差',
        MotorControlAngle: '电机控制角度',
        UploadTime: '上传时间' ,
        regist:'注册',
        userCenter: '用户中心',
        logout: '退出登录',
        language: '中文',
        indexStatistics: '指标管理',
        userManagement: '用户管理',
        totaluserlist: '总用户列表',
        feedback: '反馈处理',
        deviceManagement: '设备管理',
        totalEquipmentlist: '总设备列表',
        deviceComplaint: '设备申诉',
        companyManagement: '公司管理',
        companyAudit: '公司审核',
        companyList:'公司列表',
        agriculturalMonitoring: '农业监控',
        intelligentBasestation: '智能基站',
        accountManagement: '账号管理',
        basestationlist: '基站列表',
        basestationMonitor: '基站监控',
        productManagement: '产品管理',
        productManage: '信息管理',
        productList: '产品列表',
        versionManagement: '版本管理',
        agriculturalOperations:'农业运维',
        vehicleList: '车辆列表',
        toolsList: '农具列表',
        geographicOperations: '地理运维',
        diffServ:'司南罗网',
        serviceLog:'服务记录',
        serviveSetting:'服务配置',
        dataStatement: '用户数据',
        dataStatistics: '数据统计',
        deviceName: '设备名称',
        oemsn: 'OEM SN',
        deviceType: '设备类型',
        onlineStatus: '在线状态',
        workMode: '工作模式',
        decodeStatus: '解算状态',
        firmwareVersion: '固件版本',
        offlineTime: '离线时间',
        user: '用户',
        serialNumber: '序号',
        Operate: '操作',
        userName: '用户名',
        edit: '编辑',
        delete: '删除',
        detail: '详情',
        realName: '真实姓名',
        company: '公司',
        role: '角色',
        phoneNumber: '手机号',
        lastModifiedtime:'最近修改时间',
        ProductClassification: '产品分类',
        VersionManagement: '版本管理',
        desc:'降序排列',
        asc:'升序排列',
        deleteSort:'删除排列',
        modifier:'最后修改者',
        confirmDelete:'确定删除吗?',
        hint:'提示',
        confirm:'确定',
        cancel:'取消',
        back:'返回',
        feedbackNo: '反馈编号',
        issueType: '问题类型',
        issueDescription: '问题描述',
        status: '状态',
        submitTime: '提交时间',
        feedbackDetail: '反馈详情',
        LengthLimit: '长度在 1 到 15 ',
        oemSn: 'OEM SN',
        posx: ' L',
        posy: ' B',
        posh: 'H(米)',
        battery: '电池电量',
        workstatus: '工作状态',
        commumode: '通讯方式',
        satnum: '使用卫星数',
        ascending: '升序排列',
        descending: '降序排列',
        deleteOrder: '删除排序',
        deleteComfirm: '此操作将永久删除该文件, 是否继续?',
        prompt: '提示',
        refresh:'刷新',
        clear: '清空',
        inputParameterName: '请输入参数',
        createName: '创建者',
        showOnMap: '地图显示',
        CarId: '车辆id',
        0: '水平安装,引出线向前',
        1: '垂直安装,引出线向前',
        2: '垂直安装,引出线向下',
        placeholderBaseStation: '请输入 OEM SN',
        placeholderFarmTool: '请输入农具名称',
        goback: '返回',
        pleaseSelect: '请选择',
        allBaseStation: '全部基站',
        onlineBaseStation:'在线基站',
        offlineBaseStation: '离线基站',
        fixed: '固定',
        differential: '差分',
        online_1225: '在线',
        offline_1225: '离线',
        baseStation: '基站',
        mobileStation: '移动站',
        working: '工作中',
        notWorking: '未工作',
        longitude: '经度',
        latitude: '纬度',
        altitude: '高度',
        lasttime: '最后时间',
        radioFrequency: '电台频率',
        editFail: '编辑失败，请稍后再试',
        editSuccess: '编辑成功',
        gaode: '高德',
        baidu: '百度',
        google: '谷歌',
        DeviceSn: '设备SN',
        companyName: '公司名称',
        deviceDetail: '设备详情',
        carName: '车辆名称',
        factory: '厂家',
        model: '型号',
        useage: '使用年限',
        creator: '创建者',
        createtime: '创建时间',
        updatetime: '更新时间',
        lastAutoDriveTime: '最近自动驾驶时间',
        managerName: '管理员',
        tel: '手机号',
        taskCount: '任务统计',
        pointCount: '点数统计',
        carList: '农机列表',
        seekList: '求助列表',
        farmName: '农具名称',
        versionNum: '版本号',
        type: '类型',
        version: '软件版本',
        expirationTime:'过期时间',
        province:'设备所在地',
        workArea:'亩数',
        lastOnlineTime:'最近上线时间',
        driveCarState:'驾驶状态',
        deviceSn: 'SN',
        agreement: '协议',
        radioChannel: '信道',
        radioStatus:'模式',
        radioPower: '功率',
        host: '主机',
        port: '端口',
        insideUsername: '用户名',
        insidePassword: '密码',
        extendUsername: '用户名',
        extendPassowrd: '密码',
        Product: {
            New: '新建',
            ProductName: '产品名称',
            ProductType: '产品类型',
            ProductCreateTime: '创建时间',
            ProductUpdateTime: '更新时间',
            ProductCreator: '创建者',
            ProductOps: '操作',
            Back: '返回',
            Edit: '编辑',
            Delete: '删除',
            Cancel: '取消',
            Confirm: '确认',
            WindowsInstallPackage: 'windows安装包',
            RadioFirmware: '电台固件',
            BoardFirmware: '板卡固件',
            MotorFirmware: '电机固件',
            No:'序号',
            ProductNameSelectPlaceHolder: '请输入产品名称',
            RuleTip: {
                NameAbsence: '请输入产品名称',
                NameLength: '长度在 1 到 30 个字符',
                TypeAbsence: '请至少选择一个产品类型',
            },
            latestV:'最新版本',
            Tip: {
                LoadListFailed: '获取产品列表失败，请稍后重试！',
                AddExisted: '新建失败，该产品已经存在.',
                AddSucceeded: '新建产品成功!',
                AddError: '新建产品失败，请稍后重试！',
                UpdateSucceeded: '更新产品成功！',
                UpdateError: '更新失败，请稍后重试！',
                DeleteConfirm: '删除产品将删除产品下所有安装包，确定删除该产品吗？',
                DeleteSucceeded: '删除成功！',
                DeleteError: '删除失败，请稍后重试！',
            },
            seriesArr:['板卡','M系列','T系列','R系列','G系列','电台','电机-外购','P300系列','软件'],
            
        },
        Version: {
            Release: '发布',
            VersionName: '版本名称',
            VersionNumber: '版本号',
            Uploader: '上传者',
            UploadTime: '上传时间',
            FileSize: '文件大小',
            VersionOps: '操作',
            Back: '返回',
            Edit: '编辑',
            Delete: '删除',
            Cancel: '取消',
            Confirm: '确认',
            Farm: '农机',
            VersionRelease: '版本发布',
            VersionFile: '版本文件',
            Remark: '更新日志',
            UploadFile: '上传文件',
            UploadFileTip: '单次上传1个文件，支持 rar、pdf、exe 格式',
            ProductNameSelectPlaceHolder: '请选择产品名称',
            ProductTypeSelectPlaceHolder: '请选择产品类型',
            VersionNameTip:'仅支持数字，字母，下划线，小数点',
            VersionMark:'eg:版本号100，对应生成文件名称versionname-1.0.0.bin',
            Tip: {
                ProductAbsence: '未存在该产品，请先新建该产品。',
                NoInstallPackage: '该产品没有可用安装包。',
                LoadListFailed: '获取版本列表失败，请稍后重试！',
                LoadProductNameListFailed: '获取产品名称列表失败，请稍后重试！',
                DeleteConfirm: '确定删除该版本吗？',
                DeleteSucceeded: '删除成功！',
                DeleteError: '删除失败，请稍后重试！',
                FileExceed: '请单次上传一个文件！',
                FileLackInfo: '请先完成前三个信息填写！',
                FileFormat: '请上传规定格式！',
                ReleaseSucceeded: '版本发布成功！',
                InstallationPackageExisted: '发布失败，该版本已存在！',
                ReleaseFailed: '发布失败，文件服务器异常。请稍后再试！',
                TypeAbsence: '发布失败，该产品不存在，请重新选择存在的产品类型！',

            },
            RuleTip: {
                // VersionNumberAbsence: '请输入版本号',
                VersionNumberAbsence: '仅支持正整数，个位代表节点版本；十位代表小版本；百位及百位以上代表大版本。',
                VersionNumberType: '版本号必须为数字值',
                FileAbsence: '请上传版本文件',
                ProductNameAbsence: '请选择一个产品',
                ProductTypeAbsence: '请选择一个产品类型',
                ZeroVersionNumber: '版本号不能为0',
                versionName:'请输入版本名称'
            }
        },
        idsManage:{
            idsManage:'账号管理',
            userId:'用户名',
            options:'操作',
            dele:'删除',
            add:'新建',
            pwd:'密码',
            nameTip:'请输入用户名',
            pwsTip:'请输入密码',
            conffirm:'确定',
            cancel:'取消',
            deleCon:'确定要删除吗？'
        },
        deviceCom:{//设备申诉
            deviceAppeal:'申诉处理',
            appealNum:'申诉编号',
            appealContent:'申诉内容',
            appealTime:'创建时间',
            appealStatus:'状态',
            appealStatus1:'待处理',
            appealStatus2:'已取消',
            appealStatus3:'申诉成功',
            appealStatus4:'申诉失败',
            appealNewAdd:'新建申诉',
            appealAgreement:'合同号',
            appealProve:'购买凭证',
            appealProveUp:'上传凭证',
            appealSubmit:'提交申诉',
            appealNowStatus:'当前状态',
            appealContact:'联系方式',
            appealReasult:'申诉结果',
            appealFail:'失败原因',
            appealFeedback:'反馈申诉',
            appealSucc:'成功',
            appealError:'失败',
            appealFeedContent:'反馈内容',
            appealDetail:'申诉详情',
            confirmCancel:'确定取消吗',
            appealAgreePlaceholder:'请输入合同号',
            appealConPlaceholder:'请输入申诉内容',
            MyComplaint:'我的申诉',
            ComplaintHandle:'申诉处理',
            appealDetails:'详情',
            appealReply:'回复',
            appealConfirm:'确定'
        },
        companyManage:{//公司管理
            newCompany:'添加公司',
            companyName:'公司名',
            superManager:'超级管理员',
            phone:'手机号',
            orgCode:'组织机构代码',
            area:'所在地区',
            selectCountry:'请选择国家',
            selectState:'请选择省/州',
            selectCity:'请选择城市',
            selectArea:'请选择县',
            selectTown:'请选择街道',
            detailAddress:'详细地址',
            addressLike:'详细地址:如街道、门牌号、小区、楼栋号、单元室',
            companyDetails:'公司详情',
            assessor:'审核员',
            userCount:'用户量',
            deviceCount:'设备数',
            storageSpace:'存储空间',
            model:'模块',
            authority:'权限',
            inputCompanyName:'请输入公司名',
            approveStatus:'审核状态',
            inApprove:'审核中',
            pass:'通过',
            refused:'驳回',
            closed:'已关闭',
            editCompany:'编辑公司',
            companyFullName:'公司(全名)',
            personName:'姓名',
            superPhone:'超级管理员手机',
            approve:"审核",
            getIdentifyCode:'提示:请向系统超级管理员索要验证码',
            identifyCode:'验证码',
            inputIdentifyCode:'请输入手机验证码',
            identifyCodeError:'验证码输入有误',
            userExisted:'用户名已存在',
            companyExisted:'公司名已存在',
            phoneUsed:'手机号已使用',
            companyNameError:'公司名格式有误',
            orgCodeError:'组织机构代码只能是数字和字母',
            phoneError:'手机号格式有误',
            inputUserCount:'请输入用户量',
            inputDeviceCount:'请输入设备数',
            inputStorageSpace:'请输入存储空间',
            realNameError:'真实姓名格式有误',
            nameNotContain:'真实姓名不能含有特殊符号！',
            userNameError:'用户名格式有误',
            realNameNotEmpty:'真实姓名不能为空！',
        },
        deviceList:{ // 设备列表
            satnum: '卫星数量',
            deviceIdNo: '设备ID号',
            deviceName:'设备名称',
            deviceType:'设备类型',
            deviceOnlineStatus:'在线状态',
            deviceMode:'工作模式',
            deviceSolution:'解算状态',
            deviceFirmware:'固件版本',
            systemBoardVersion: 'Boot版本',
            commumode: '通信方式',
            deviceOfflineTime:'离线时间',
            deviceUser:'用户',
            deviceOperation:'操作',
            deviceEdit:'编辑',
            deviceSN:'设备SN',
            deviceGroup:'组',
            deviceComment:'备注',
            deviceDetail:'详情',
            deviceStatus:'状态',
            deviceLastUser:'最后使用者',
            deviceLastStatus:'最后工作模式',
            deviceLastLocation:'最后坐标位置',
            deviceListName:'设备列表',
            deviceDel:'删除排序',
            deviceDecs:'降序排序',
            deviceAcs:'升序排序',
            deviceSign:'注册',
            deviceLong:'远程管理',
            deviceOnline:'在线',
            deviceOffline:'离线',
            deviceStation:'基准站',
            deviceMove:'移动站',
            deviceJie1:'无效解',
            deviceJie2:'单点解',
            deviceJie3:'差分解',
            deviceJie4:'浮动解',
            deviceJie5:'固定解',
            deviceJie6:'惯导解',
            deviceJie7:'伪距差分',
            deviceJie8:'未知',
            deviceNoAru:'权限不足',
            deviceListTitle:'设备列表',
            deviceErrorTip:'名称格式有误,不能含有特殊字符',
            deviceNamePlaceholder:'请输入设备名称',
            deviceSnPlaceholder:'请输入设备SN',
            deviceOemSnPlaceholder:'请输入OEM SN',
            devicePnPlaceholder:'请输入设备PN',
            deviceCommentPlaceholder:'请输入备注',
            deviceSnTip:'sn必须为8-16位的数字',
            tcpOffLine:'TCP离线',
            // 编辑 详情
            deviceTypeNo:'型号',
            deviceOneReceive:'一体化接收机',
            deviceOemtype:'OEM类型',
            deviceTerms:'过期期限',
            deviceVersion:'系统板版本',
            deviceDefaultGroup:'默认组',
            deviceNullGroup:'未分组',
            deviceGroupName:'组名',
            // 总设备列表
            deviceListAll:'总设备列表',
            deviceExport:'导出',
            connectDevice: '连接设备？',
            hint: '提示',
            success: '连接成功!',
            failed: '连接失败',
            connecting: '正在远程中!',
            occupied: '设备占用!'
        }, 
        tips:{ //提示语
            beforeSubmitTip:'请填好数据后再提交！',
        },
       
    },
   
};


export default zh